<a href="https://colab.research.google.com/github/arkshisharma/C-Programs-Semester-1/blob/main/Copy_of_Generative_Ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#my_list = [78, 57,89,34,23]     #a list can store elements of different data types. it does not matter whether the elements are all integers like in my_list or mixed like in mixed_list . python only checks the container type, not the type of element inside it.
type(my_list)

list

In [ ]:
mixed_list = [ "apple", 23, 3.14, True ,None]
type(mixed_list)

list

In [ ]:
print(my_list)

[78, 57, 89, 34, 23]


In [ ]:
#lens()--this function find the length of the list
len(my_list)

5

In [ ]:
#positive indexing
my_list = [78 , 59 , 23 ,64]
print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])

78
59
23
64


In [ ]:
#negative indexing
my_list = [78,59,23,64]
print(my_list[0])
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])

78
64
23
59


In [ ]:
my_list = [2,3,4,7,8]                           # start from 0 stop at 5 step is 1
my_list[0:5:1]


[2, 3, 4, 7, 8]

In [ ]:
#step size by default is one               # start = index 0 , stop = index 5 (but stop is not exclusive so it does not include element at index 5)       # both [0:5] and [:5] means take elements from start up to index (not including 5 )
my_list[0:5]

[2, 3, 4, 7, 8]

In [ ]:
my_list[:5]                                      #if you did not mention starting index and only mention endind index then slicing will start from the beginning of the sequence(index 0) and go up to ending index -1     //list[:n] means from start index 0 to n-1..  //list[m:] means from m to the end..  //list[:] means the entire list

[2, 3, 4, 7, 8]

In [ ]:
my_list[: :-1]                            # if you want to print in opposite direction # if you use -1 it means move backward one element at a time

[8, 7, 4, 3, 2]

In [ ]:
#function in list
#min()--this function finds the minimum number of items in list
my_list = [2,3,4,7,8,9]
min(my_list)

2

In [ ]:
#max()--this function maximum number of item in list
my_list = [2,3,4,7,8,9]
max(my_list)


9

In [ ]:
#sum()--this function work on numerical
sum(my_list)

33

In [ ]:
#sorted()--arranging list in increasing or decreasing order
my_list = (9,7,2,3,6,10,5)
sorted(my_list, reverse = True)

[10, 9, 7, 6, 5, 3, 2]

In [ ]:
#append()--this method add the item end of the list
my_list = [3,45,89,23]
my_list.append(100)
my_list

[3, 45, 89, 23, 100]

In [ ]:
#sort()--arranging list in increasing or decreasing order
list1 = [8,6,3,2,9,10,1]
list1.sort()
list1

[1, 2, 3, 6, 8, 9, 10]

In [ ]:
#extend()--this method merge a list into another list
list1 = [90, 87, 65,43]
list2= [56, 45, 89, 60]
list1.extend(list2)
list1


[90, 87, 65, 43, 56, 45, 89, 60]

In [ ]:
#pop()--this method remove item from the list, take indx as a argument
my_list = [90, 80, 85, 23, 89]
my_list.pop()

89

In [ ]:
my_list

[90, 80, 85, 23]

In [ ]:
my_list.pop(0)

90

In [ ]:
my_dict = {"HP":"SHM","PU":"CHD","UP":"LUCK"}
type(my_dict)

dict

In [ ]:
print(my_dict)

{'HP': 'SHM', 'PU': 'CHD', 'UP': 'LUCK'}


In [ ]:
#how to find value with help of key
print(my_dict["HP"])
print(my_dict["PU"])
print(my_dict["UP"])

SHM
CHD
LUCK


In [ ]:
#dictionary method
#keys()--this method return the list of keys in dictionary object
list(my_dict.keys())

['HP', 'PU', 'UP']

In [ ]:
#values()--this method return the list of values in dictionary object
my_dict.values()

dict_values(['SHM', 'CHD', 'LUCK'])

In [ ]:
#items()-this method return the list of keys and values
list(my_dict.items())

[('HP', 'SHM'), ('PU', 'CHD'), ('UP', 'LUCK')]

In [ ]:
#get()--this method return the value and take key as a argument
my_dict.get("HP")

'SHM'

In [ ]:
my_dict.get("MP","Not found")

'Not found'

In [ ]:
my_dict = {"Name":"Amit","state":"HP"}
my_dict.update({"College":"Shoolini university"})
my_dict

{'Name': 'Amit', 'state': 'HP', 'College': 'Shoolini university'}

In [ ]:
my_dict.update({"Name":"Kritika"})
my_dict

{'Name': 'Kritika', 'state': 'HP', 'College': 'Shoolini university'}

In [ ]:
#zip()--this function take pair of list as argument and return object
name_list = ["Amit","Kritka","Roshan"]
college_list = ["shoolini" "LR","MMU"]
dict(zip(name_list , college_list))

{'Amit': 'shooliniLR', 'Kritka': 'MMU'}

In [ ]:
#conditional statement
#if statement--if statement is true then it execute
#elif staement--if conditional is true then it execute
#else statement--if both statement,if and elifcondition is false then it execute
age = int(input("Enter your age"))
if age<18:
  print("you are too young to marry")
elif age>60:
  print("you are too old to marry")
else:
  print("we will find a perfect match for you")

Enter your age17
you are too young to marry


In [ ]:
#loop help to execute block of code repeatedly
my_name = "Amit"
print(my_name[0])
print(my_name[1])
print(my_name[2])
print(my_name[3])

A
m
i
t


In [ ]:
#for loop in python is used iterate oyer a sequence(string' list' tuple)
my_name = "Amit"
for i in my_name:
  print(i)

A
m
i
t


In [ ]:
for i in range(0, 5, 1):
  print(i)

0
1
2
3
4


In [ ]:
my_sub = "python"
for i in range(len(my_sub)):
  print(my_sub[i],"->",i)


p -> 0
y -> 1
t -> 2
h -> 3
o -> 4
n -> 5


In [ ]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [ ]:
#while loop--this loop is used to execute a block of code repeatedly until
# a given condition is true
i = 0
while i<5:
  print(i)
  i+=1

0
1
2
3
4


In [ ]:
#loop control statement
#Break--break the loop
#continue--skip current iteration
#pass--only pass the code
i = 0
while i<6:
  i+=1
  if i == 3:
    break
    print(i)
  else:
      print(i)

1
2


In [ ]:
i = 0
while i<6:
  i+=1
  if i == 3:
    continue
    print(i)
  else:
      print(i)

1
2
4
5
6


In [ ]:
i = 0
while i<6:
  i+=1
  if i == 3:
    pass
    print(i)
  else:
      print(i)

1
2
3
4
5
6


In [ ]:
#user defined function without argument
def add():
  a = int (input("Enter first number:"))
  b = int (input("Enter second number:"))
  return a+b

In [ ]:
add()

Enter first number:10
Enter second number:3


13

In [ ]:
#positional argument ---the argument that are pass to a function
#these value paDivision", a/b)
return "our calculation is complete"



SyntaxError: 'return' outside function (ipython-input-1583032067.py, line 3)

In [ ]:
print(calculator(10,5))

NameError: name 'calculator' is not defined

In [ ]:
#default argument--these argument value given during defined a function
def area_perimeter(width = 2, height = 4):
  area = width*height
  perimeter = 2*(width+height)
  return area,perimeter

In [ ]:
area_perimeter(8)

(32, 24)

In [ ]:
#keyword argument
def interest(p, r, t):
  i = (p*r*t)/100
  return i

In [ ]:
interest(r =10, t = 2, p = 1000)

200.0

In [ ]:
#mixed argument
interest(1000, t = 2, r = 10)


200.0

In [ ]:
#non keyword positional variable length argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

In [ ]:
test(1,7,8,9,10,11)

(1, 7, 8, 9, 10, 11)
6
<class 'tuple'>


In [ ]:
my_tuple = (4,5,7,8)
for i in my_tuple:
  print(i)

4
5
7
8


In [ ]:

def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

In [ ]:
sum_number(3,4,5,6,2)

20

In [ ]:
#keyword variable length argument
#keyword variable length argument behave as dictionary
def test(**kwargs):
  print(kwargs)
  print(len(kwargs))
  print(type(kwargs))


In [ ]:
test(a = 10, b = 20, c = 30)

{'a': 10, 'b': 20, 'c': 30}
3
<class 'dict'>


In [ ]:
def pass_students(**kwargs):
  pass_student_list = []
  for name,marks in kwargs.items():
    if marks>33:
      pass_student_list.append(name)
  return pass_student_list

In [ ]:
pass_students(A = 40 , B = 40 , C = 30)

['A', 'B']

In [ ]:
# Library is the collection of attribute, property, function , method , class, file, module and package.
#numpy -> Numerical python. it is used for mathematics ..data structure of numpy multidimensional array.
#importnnumpy as np  here as is a keyword which is used to name of alias..
#it is keyword which is used to import module, package or library..

In [ ]:
import numpy as np

In [ ]:
#array
oned_array = np.array([1, 2 ,3])
print(oned_array)

[1 2 3]


In [ ]:
rank1_vector = np.array ([1,2,3])
print(rank1_vector)

[1 2 3]


In [ ]:
#ndim--find the dimensipn of the vector
print(rank1_vector.ndim)

1


In [ ]:
#size--total no. of item
print(rank1_vector.size)

3


In [ ]:
print(rank1_vector.transpose())


[1 2 3]


In [ ]:
row_vector = np.array([[1,2,3]])
print(row_vector)

[[1 2 3]]


In [ ]:
print(row_vector.ndim)

2


In [ ]:
print(row_vector.size)

3


In [ ]:
print(row_vector.transpose())

[[1]
 [2]
 [3]]


In [ ]:
print(row_vector)
print(row_vector.shape)

[[1 2 3]]
(1, 3)


In [ ]:
print(row_vector[0])

[1 2 3]


In [ ]:
#two dimensional array
twod_array = np.array([[1,2,3],[8,9,2]])
print(twod_array)

[[1 2 3]
 [8 9 2]]


In [ ]:
print(twod_array[0] [2])

3


In [ ]:
print(twod_array[1] [0])

8


In [ ]:
import numpy as np

In [ ]:
mat1= np.matrix("1,2,3;4,5,6;7,8,9")
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
zeros_array = np.zeros((3,3),dtype=int)
print(zeros_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_array = np.ones((3,3),dtype = int)
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
my_array = np.full((3,3), 100)
print(my_array)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [ ]:
my_array = np.array([1,2,3,4])
print(my_array)

[1 2 3 4]


In [ ]:
power_array = np.power(my_array,2)
print(power_array)

[ 1  4  9 16]


In [ ]:
print(my_array)

[1 2 3 4]


In [ ]:
exp_data=np.exp(my_array)
print(exp_data)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
print(my_array)

[1 2 3 4]


In [ ]:
log_array = np.log(my_array)
print(log_array)

[0.         0.69314718 1.09861229 1.38629436]


In [ ]:
log2_array = np.log2(my_array)
print(log2_array)


[0.        1.        1.5849625 2.       ]


In [ ]:
log10_array = np.log10(my_array)
print(log10_array)

[0.         0.30103    0.47712125 0.60205999]


In [ ]:
randint_array = np.random.randint(2,10, (3,3))
print(randint_array)


[[5 2 7]
 [2 3 7]
 [7 9 6]]


In [ ]:
random_array = np.random.random((3,3))
print(random_array)

[[0.52740263 0.17429695 0.52269509]
 [0.0072194  0.24651232 0.10351513]
 [0.42431526 0.81844601 0.47323965]]
